apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-staging-02.api.letsencrypt.org/directory
    email: Nikheel.Jain@shl.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          podTemplate:
            spec:
              nodeSelector:
                "kubernetes.io/os": linux
